version: '3.8'

services:

  django:
    image: cyprus
    build:
      context: .
      dockerfile: Dockerfile
    command: ['python', 'manage.py', 'runserver', '0.0.0.0:8000']
    ports:
      - '8000:8000'
    env_file:
      - .env.dev
    volumes:
      - ./:/app/

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    image: cyprus
    command: ['celery', '-A', 'balance', 'worker', '-l', 'info']
    env_file:
      - .env.dev
    depends_on:
      - redis
    volumes:
      - ./:/app/