# Generated by Django 4.1.1 on 2022-09-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "hash",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("ledger_index", models.CharField(max_length=200)),
                ("Amount", models.CharField(max_length=200)),
                ("Account", models.CharField(max_length=200)),
                ("Destination", models.CharField(max_length=200)),
                (
                    "DestinationTag",
                    models.CharField(default=None, max_length=200, null=True),
                ),
                ("Fee", models.CharField(max_length=200)),
            ],
        ),
    ]
