# Generated by Django 4.1.1 on 2022-09-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction", name="Amount", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction", name="Fee", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction", name="ledger_index", field=models.IntegerField(),
        ),
    ]
